# Generated by Django 5.2.12 on 2026-04-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bill_billitem_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='billitem',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
