# Generated by Django 5.2.12 on 2026-05-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_billitem_product_id_billitem_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer_addr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
