# Generated by Django 5.2.12 on 2026-05-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingsession',
            old_name='online_sales',
            new_name='fonepay_sales',
        ),
        migrations.RemoveField(
            model_name='billingsession',
            name='total_discount',
        ),
    ]
