# Generated by Django 5.2.12 on 2026-05-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_rename_online_sales_billingsession_fonepay_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsession',
            name='session_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
