# Generated by Django 5.2.12 on 2026-04-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_balance', models.FloatField()),
                ('cash_sales', models.FloatField()),
                ('pos', models.FloatField()),
                ('fonepay', models.FloatField()),
                ('credit', models.FloatField()),
                ('total_sales', models.FloatField()),
                ('excess_less', models.FloatField()),
                ('expenses', models.FloatField()),
                ('deposited_bank', models.FloatField()),
                ('given_other', models.FloatField()),
                ('closing_balance', models.FloatField()),
            ],
        ),
    ]
