# Generated by Django 5.2.12 on 2026-05-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_summary_delete_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='date',
        ),
        migrations.AddField(
            model_name='summary',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
