# Generated by Django 5.2.12 on 2026-05-29 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_summary_date_summary_session_id'),
        ('session', '0003_billingsession_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='session_id',
        ),
        migrations.AddField(
            model_name='summary',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='session.billingsession'),
        ),
    ]
