# Generated by Django 5.2.12 on 2026-05-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('pan_no', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
